### ISSUE TITLE
BadFactForSegmentError if the metric name is not supported for segment_values

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#38]
can you raise an appropriate exception if a bad metric is requested for `segment_values`

let's raise `BadFactForSegmentError` instead of `FieldSegmentError`

i believe this should mean that the requested metric is NOT one of Revenues, NetIncomeAttributableToParent and NetIncomeLoss (just by looking at your code for `XBRL.fact_labels`)

**Comment by gpkc** [comment]
I'm not sure, my idea is to move all metrics to `fact_labels`. That is a refactoring that needs to be done eventually, because the way pysec deals with xbrl is very brittle hard to maintain.

Therefore, the logic I've put in place to check if a given metric doesn't have segments, and raise `FieldSegmentError`, is pretty much temporary.

Unless you're suggesting me to replace `FieldSegmentError` with `BadFactForSegmentError`, that's easy to do.

**Comment by kut** [comment]
I had meant that if the metric isn’t “Revenues” or “Gross Profit” or
“NetIncome” or “NetIncomeAttributableToParent” then raise a different error
instead of the generic FieldSegmentError

**Comment by gpkc** [comment]
@kut on the refactored version, this is no longer needed, as all metrics can be queried for segments. They are all in the `fact_labels` dict.

**Comment by kut** [comment]
Ok can close then
