### ISSUE TITLE
Segment values float bug

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#53]
https://visorco.slack.com/archives/C5JCB30LR/p1534016590000043

**Comment by gpkc** [comment]
@kut the problem is this fact:
`<us-gaap:NetIncomeLoss contextRef="FD2013Q4YTD_us-gaap_StatementBusinessSegmentsAxis_bac_MergerAndRestructuringChargesMember" id="Fact-42196F50D7C985306B446B935893CB1C" unitRef="usd" xsi:nil="true"/>`
Those `nil` facts have no associated value, that's why it's returning a `None` when my code asks for its value.
Its context is:
```
 <xbrli:context id="FD2013Q4YTD_us-gaap_StatementBusinessSegmentsAxis_bac_MergerAndRestructuringChargesMember">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.sec.gov/CIK">0000070858</xbrli:identifier>
      <xbrli:segment>
        <xbrldi:explicitMember dimension="us-gaap:StatementBusinessSegmentsAxis">bac:MergerAndRestructuringChargesMember</xbrldi:explicitMember>
      </xbrli:segment>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:startDate>2013-01-01</xbrli:startDate>
      <xbrli:endDate>2013-12-31</xbrli:endDate>
    </xbrli:period>
  </xbrli:context>
```
Should I exclude those, return None as their value, or something else?

**Comment by kut** [comment]
Just don’t return those values

**Comment by gpkc** [comment]
@kut not sure what you mean. Are they supposed to get in the `bad_contexts` list, or simply removed similar to what we do with the `pro forma` ones?
